[ENH] Made base_api_url an environment variable
neurobagel/query-tool-ai pull request #37
Opened 2024-08-10 06:22 UTC by Raya679

- Closes #35 

Changes proposed in this pull request:

- Made base_api_url an environment variable.
- Updated documentation.

## Checklist
_This section is for the PR reviewer_

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2024-08-10 07:12 UTC, Raya679 commented
Hii @rmanaem, I have made the base_api_url an environment variable here. Please take a look and suggest any changes if required.
Thanks!

2024-08-13 15:34 UTC, rmanaem commented on app/api/url_generator.py
> +    base_api_url = os.getenv("BASE_API_URL", "None")
```suggestion
    base_api_url = os.getenv("NB_API_QUERY_URL", "None")
```

2024-08-13 15:35 UTC, rmanaem commented on README.md
> +   | `BASE_API_URL`                 | string  | Yes                                       | `None`                | `https://api.neurobagel.org/query/?`
```suggestion
   | `NB_API_QUERY_URL`                 | string  | Yes                                       | `None`                | `https://api.neurobagel.org/query/?`                                               |
```

2024-08-13 15:36 UTC, rmanaem commented on tests/test_url_generator.py
> +    with patch.dict("os.environ", {"BASE_API_URL": "https://api.neurobagel.org/query/?"}):
```suggestion
    with patch.dict("os.environ", {"NB_API_QUERY_URL": "https://api.neurobagel.org/query/?"}):
```

2024-08-13 15:42 UTC, rmanaem requested changes
Thanks for the PR @Raya679!
:cherries: I think it's a good idea to have a way to make sure the new env var is set, throw an error to inform the user in case it's not and a test for that. Since the implementation simply concatenates the env var with the output from the llm to send the request, we can end up with http errors if the env var is not set properly. Let me know what you think.

2024-08-13 16:50 UTC, Raya679 commented
Hi @rmanaem , thanks for the review!
I have made the changes suggested. Also I have removed the default value `None` of NB_API_QUERY_URL since now we get an error if it is not set.

2024-08-13 17:03 UTC, rmanaem requested changes
:cherries:

2024-08-13 17:03 UTC, rmanaem commented on app/api/url_generator.py
> +
I think it's better practice to raise a runtime error here similar to what we have in the api and check for that in the test:
https://github.com/neurobagel/api/blob/c7c1839d4a013c7a3d3b0567174dbf24e81c97f2/app/main.py#L92-L99

2024-08-13 17:34 UTC, Raya679 commented
Hii @rmanaem, I have made the changes.
Please take a look and do suggest any changes if required.

Thanks!

2024-08-13 19:40 UTC, rmanaem approved these changes
:cook:

2024-08-14 04:23 UTC, merged